name: SMPCore
version: '1.0-SNAPSHOT'
main: me.moontimer.smpcore.SmpCorePlugin
api-version: '1.21'

commands:
  spawn:
    description: Teleportiere dich zum Spawn.
    usage: /spawn
    permission: smpcore.spawn.use
  sethome:
    description: Setze ein Zuhause.
    usage: /sethome [name]
    permission: smpcore.home.sethome
  home:
    description: Teleportiere dich zu einem Zuhause.
    usage: /home [name]
    permission: smpcore.home.use
  delhome:
    description: Loesche ein Zuhause.
    usage: /delhome <name>
    permission: smpcore.home.delete
  homes:
    description: Liste deiner Homes.
    usage: /homes
    permission: smpcore.home.list
  back:
    description: Zurueck zur letzten Position.
    usage: /back
    permission: smpcore.back.use
  tpa:
    description: Teleport-Anfrage senden.
    usage: /tpa <player>
    permission: smpcore.tpa.send
  tpahere:
    description: Spieler zu dir einladen.
    usage: /tpahere <player>
    permission: smpcore.tpa.here
  tpaccept:
    description: Teleport-Anfrage annehmen.
    usage: /tpaccept [player]
    permission: smpcore.tpa.accept
  tpdeny:
    description: Teleport-Anfrage ablehnen.
    usage: /tpdeny [player]
    permission: smpcore.tpa.deny
  tpacancel:
    description: Eigene Anfrage abbrechen.
    usage: /tpacancel
    permission: smpcore.tpa.cancel
  warp:
    description: Teleportiere dich zu einem Warp.
    usage: /warp <name>
    permission: smpcore.warp.use
  setwarp:
    description: Setze einen Warp.
    usage: /setwarp <name>
    permission: smpcore.warp.set
  delwarp:
    description: Loesche einen Warp.
    usage: /delwarp <name>
    permission: smpcore.warp.delete
  warps:
    description: Liste der Warps.
    usage: /warps
    permission: smpcore.warp.list
  rtp:
    description: Zufallsteleport.
    usage: /rtp [world]
    permission: smpcore.rtp.use
  msg:
    description: Private Nachricht senden.
    usage: /msg <player> <message>
    aliases: [tell, w]
    permission: smpcore.msg.use
  reply:
    description: Auf letzte Nachricht antworten.
    usage: /reply <message>
    aliases: [r]
    permission: smpcore.reply.use
  ignore:
    description: Spieler ignorieren.
    usage: /ignore <player>
    permission: smpcore.ignore.use
  ignorelist:
    description: Ignorierte Spieler anzeigen.
    usage: /ignorelist
    permission: smpcore.ignore.use
  socialspy:
    description: SocialSpy umschalten.
    usage: /socialspy
    permission: smpcore.staff.socialspy
  mutechat:
    description: Globalen Chat muten.
    usage: /mutechat [duration] [reason]
    permission: smpcore.mod.mutechat
  gamemode:
    description: Gamemode aendern.
    usage: /gamemode <0|1|2|3> [player]
    aliases: [gm, gms, gmc, gma, gmsp]
    permission: smpcore.staff.gamemode
  fly:
    description: Flugmodus umschalten.
    usage: /fly [player]
    permission: smpcore.fly.self
  tp:
    description: Zu einem Spieler teleportieren.
    usage: /tp <player> | /tp <x> <y> <z> [world]
    permission: smpcore.staff.tp
  tphere:
    description: Spieler zu dir teleportieren.
    usage: /tphere <player>
    permission: smpcore.staff.tphere
  whois:
    description: Spielerinfos anzeigen.
    usage: /whois <player>
    permission: smpcore.staff.whois
  info:
    description: Staff-Info zu einem Spieler.
    usage: /info <player>
    permission: smpcore.staff.info
  heal:
    description: Spieler heilen.
    usage: /heal [player]
    permission: smpcore.staff.heal
  feed:
    description: Spieler fuettern.
    usage: /feed [player]
    permission: smpcore.staff.feed
  speed:
    description: Lauf-/Fluggeschwindigkeit setzen.
    usage: /speed <0-10> [player]
    permission: smpcore.staff.speed
  invsee:
    description: Inventar eines Spielers oeffnen.
    usage: /invsee <player>
    permission: smpcore.staff.invsee
  endersee:
    description: Endertruhe eines Spielers oeffnen.
    usage: /endersee <player>
    permission: smpcore.staff.endersee
  vanish:
    description: Vanish umschalten.
    usage: /vanish [player]
    permission: smpcore.staff.vanish
  vtp:
    description: Vanish + Teleport zu Spieler.
    usage: /vtp <player>
    permission: smpcore.staff.vtp
  tpall:
    description: Alle Spieler zu dir teleportieren.
    usage: /tpall
    permission: smpcore.staff.tpall
  tppos:
    description: Teleport zu Koordinaten.
    usage: /tppos <x> <y> <z> [world]
    permission: smpcore.staff.tppos
  clearchat:
    description: Chat leeren.
    usage: /clearchat
    permission: smpcore.staff.clearchat
  ban:
    description: Spieler bannen.
    usage: /ban <player> [reason] [-s]
    permission: smpcore.mod.ban
  tempban:
    description: Spieler tempbannen.
    usage: /tempban <player> <duration> [reason] [-s]
    permission: smpcore.mod.tempban
  unban:
    description: Spieler entbannen.
    usage: /unban <player>
    permission: smpcore.mod.unban
  mute:
    description: Spieler muten.
    usage: /mute <player> [reason] [-s]
    permission: smpcore.mod.mute
  tempmute:
    description: Spieler tempmuten.
    usage: /tempmute <player> <duration> [reason] [-s]
    permission: smpcore.mod.tempmute
  unmute:
    description: Spieler entmuten.
    usage: /unmute <player>
    permission: smpcore.mod.unmute
  warn:
    description: Spieler verwarnen.
    usage: /warn <player> <reason>
    permission: smpcore.mod.warn
  unwarn:
    description: Letzte Verwarnung entfernen.
    usage: /unwarn <player>
    permission: smpcore.mod.warn
  clearwarnings:
    description: Alle Verwarnungen entfernen.
    usage: /clearwarnings <player>
    permission: smpcore.mod.warn
  warnings:
    description: Verwarnungen anzeigen.
    usage: /warnings <player> [page]
    permission: smpcore.mod.history
  kick:
    description: Spieler kicken.
    usage: /kick <player> [reason]
    permission: smpcore.mod.kick
  reasons:
    description: Vorgefertigte Ban- und Mute-Gruende anzeigen.
    usage: /reasons [ban|mute]
    permission: smpcore.mod.reasons
  history:
    description: Verlauf eines Spielers anzeigen.
    usage: /history <player> [page]
    permission: smpcore.mod.history
  staffhistory:
    description: Verlauf eines Staffs anzeigen.
    usage: /staffhistory <staff> [page]
    permission: smpcore.mod.history
  banlist:
    description: Aktive Bans anzeigen.
    usage: /banlist [page]
    permission: smpcore.mod.history
  balance:
    description: Kontostand anzeigen.
    usage: /balance
    permission: smpcore.economy.balance
  pay:
    description: Geld senden.
    usage: /pay <player> <amount>
    permission: smpcore.economy.pay
  help:
    description: SMP-Core Hilfe.
    usage: /help
  menu:
    description: Staff Menu oeffnen.
    usage: /menu [player]
    permission: smpcore.staff.menu
  tablist:
    description: Tablist bearbeiten.
    usage: /tablist <setheader|setfooter|reload> <text>
    permission: smpcore.staff.tablist
  motd:
    description: MOTD bearbeiten.
    usage: /motd <set|reload> <text>
    permission: smpcore.staff.motd
  smpcore:
    description: SMP-Core Admin.
    usage: /smpcore <reload|migrate>
    permission: smpcore.admin

permissions:
  smpcore.spawn.use:
    default: true
  smpcore.home.sethome:
    default: true
  smpcore.home.use:
    default: true
  smpcore.home.delete:
    default: true
  smpcore.home.list:
    default: true
  smpcore.tpa.send:
    default: true
  smpcore.tpa.here:
    default: true
  smpcore.tpa.accept:
    default: true
  smpcore.tpa.deny:
    default: true
  smpcore.tpa.cancel:
    default: true
  smpcore.back.use:
    default: true
  smpcore.rtp.use:
    default: true
  smpcore.msg.use:
    default: true
  smpcore.reply.use:
    default: true
  smpcore.ignore.use:
    default: true
  smpcore.warp.use:
    default: true
  smpcore.warp.list:
    default: true
  smpcore.warp.set:
    default: op
  smpcore.warp.delete:
    default: op
  smpcore.home.limit.*:
    default: false
  smpcore.tpa.cooldown.bypass:
    default: op
  smpcore.rtp.cooldown.bypass:
    default: op
  smpcore.rtp.world.*:
    default: op
  smpcore.teleport.bypass.warmup:
    default: op
  smpcore.fly.self:
    default: false
  smpcore.staff.fly:
    default: op
    children:
      smpcore.fly.self: true
  smpcore.staff.gamemode:
    default: op
  smpcore.staff.heal:
    default: op
  smpcore.staff.feed:
    default: op
  smpcore.staff.speed:
    default: op
  smpcore.staff.tp:
    default: op
  smpcore.staff.tphere:
    default: op
  smpcore.staff.whois:
    default: op
  smpcore.staff.info:
    default: op
  smpcore.staff.socialspy:
    default: op
  smpcore.staff.menu:
    default: op
  smpcore.staff.notify:
    default: op
  smpcore.staff.invsee:
    default: op
  smpcore.staff.endersee:
    default: op
  smpcore.staff.vanish:
    default: op
  smpcore.staff.vanish.others:
    default: op
  smpcore.staff.vanish.see:
    default: op
  smpcore.staff.vtp:
    default: op
  smpcore.staff.tpall:
    default: op
  smpcore.staff.tppos:
    default: op
  smpcore.staff.clearchat:
    default: op
  smpcore.staff.tablist:
    default: op
  smpcore.staff.motd:
    default: op
  smpcore.combat.bypass:
    default: op
  smpcore.mod.ban:
    default: op
  smpcore.mod.tempban:
    default: op
  smpcore.mod.unban:
    default: op
  smpcore.mod.mute:
    default: op
  smpcore.mod.tempmute:
    default: op
  smpcore.mod.unmute:
    default: op
  smpcore.mod.warn:
    default: op
  smpcore.mod.kick:
    default: op
  smpcore.mod.reasons:
    default: op
  smpcore.mod.history:
    default: op
  smpcore.mod.mutechat:
    default: op
  smpcore.economy.balance:
    default: true
  smpcore.economy.pay:
    default: true
  smpcore.config.reload:
    default: op
  smpcore.db.migrate:
    default: op
  smpcore.admin:
    default: op

